version: '3'
services:
  prisma:
    image: prismagraphql/prisma:1.32
    restart: always
    ports:
    - "4466:4466"
    environment:
      PRISMA_CONFIG: |
        port: 4466
        # uncomment the next line and provide the env var PRISMA_MANAGEMENT_API_SECRET=my-secret to activate cluster security
        # managementApiSecret: my-secret
        databases:
          default:
            connector: postgres
            host: ec2-174-129-208-118.compute-1.amazonaws.com
            database: d19qlui8chga3e
            schema: renterii$prod
            user: bqecdyrrtedmec
            password: e46ae132e0c241f03bfa4939d3510bb6ccd97c4a29023a50fe8a405a638ebd7f
            ssl: true
            rawAccess: true
            port: '5432'
            migrations: true